# Site settings
title:              Gulp Build Manager
description:        Easy to use, configurable gulp task manager.
repo:               "https://github.com/shnam7/gulp-build-manager/tree/master"
url:                "https://shnam7.github.io/gulp-build-manager"
baseurl:            "/gulp-build-manager"

# Project settings
# source and destination is set by gulpfile.js
#source:           docs
#destination:      docs/gulp-build-manager
# version:            4.0
encoding:           utf-8
markdown:           kramdown
permalink:          pretty
baseurl:            "/gulp-build-manager"
safe:               true
exclude:            ['_assets', 'Gemfile*', 'gbmconfig.js', 'gulpfile.js', "tsconfig.js"]
defaults:
    -
        scope:
            path:   ""
        values:
            layout: docs

# Module settings
kramdown:
    input: GFM
    hard_wrap: true
    auto_ids: false

keep_files:         []

# Custom variable
