# Site settings
title:            Gulp Build Manager
description:      Easy to use, flexible gulp task manager.
url:              "https://shnam7.github.io/gulp-build-manager"
baseurl:          ""    # root folder relative to local server
repo:             "https://github.com/shnam7/gulp-build-manager"

# Project settings
# source and destination is set by gulpfile.js
source:           .
destination:      ../_gh_pages
version:          2.0.0.alpha.1
encoding:         utf-8
exclude:          [assets, '*.map', 'gulpfile.*']
markdown:         kramdown
highlighter:      rouge
permalink:        pretty
defaults:
  - scope:
      path:       "" # All files in the scope
    values:
      layout:     "docs"
plugins:          _plugins
plugins_dir:      _plugins
keep_files: [css,js,images]

# Custom variables

# Module settings
kramdown:
  input: GFM
  auto-ids: false

#redcarpet:
#  extensions: ["footnotes", "smart", "tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

#sass:
#  style: compressed
